### ISSUE TITLE
Change Metabox label in CPT

### ISSUE THREAD

**Issue by EugenioPetulla** [CodeAtCode/Glossary#10]
From *Glossary* to *Glossary auto-link settings*
![schermata da 2016-02-17 19-27-12](https://cloud.githubusercontent.com/assets/3589467/13120140/a28fa2b2-d5ac-11e5-9be5-10aa00dacce2.png)

**Comment by Mte90** [comment]
![screenshot10](https://cloud.githubusercontent.com/assets/403283/13120375/d9d483e0-d5ad-11e5-875c-bbcd91bcc430.png)

**Comment by EugenioPetulla** [comment]
:+1:
