### ISSUE TITLE
Check and change slug for glossary CPT

### ISSUE THREAD

**Issue by EugenioPetulla** [CodeAtCode/Glossary#11]
Single pages without base and archive page slug must be *glossary*

**Comment by Mte90** [comment]
whats?

[![selfie-1](http://i.imgur.com/4to7Jgh.png)](https://github.com/thieman/github-selfies/)

**Comment by EugenioPetulla** [comment]
Single page must have only his name in the url, no base. Like this: http://mywebsi.te/term-title

Archive page must have glossary slug. Like this: http://mywebsi.te/glossary/

**Comment by Mte90** [comment]
[![selfie-0](http://i.imgur.com/e26hNae.png)](https://github.com/thieman/github-selfies/)

**Comment by EugenioPetulla** [comment]
We have to revert this change, it cause a bug with multisite. Look at the demo now, the permalink are just messed up.

Revert the change and set the URL BASE like this:

http://mysi.te/glossary/my-term <- *single page*
http://mysi.te/glossary/ <- *Archive page*
