### ISSUE TITLE
No possibility to autolink glossary terms into archive glossary page

### ISSUE THREAD

**Issue by EugenioPetulla** [CodeAtCode/Glossary#13]
I cannot find the option to activate the autolink function into glossary single pages
![schermata da 2016-02-17 23-11-39](https://cloud.githubusercontent.com/assets/3589467/13126707/d54009da-d5cb-11e5-9294-f54bf9c2f2a6.png)

**Comment by Mte90** [comment]
[![selfie-0](http://i.imgur.com/trA5XqR.png)](https://github.com/thieman/github-selfies/)

**Comment by EugenioPetulla** [comment]
Doesn't work on Glossary Archive excerpts.

Look at the page: http://codeat.co/glossary/?post_type=glossary

No links at all... maybe we have to set another conditional detecting for this kind of page. ;)
![schermata da 2016-02-18 14-03-59](https://cloud.githubusercontent.com/assets/3589467/13144110/cec66518-d648-11e5-9363-af15c138ec79.png)

**Comment by Mte90** [comment]
https://github.com/CodeAtCode/Glossary/blob/master/public%2Fclass-glossary.php#L285 There is the option for the archive of the glossary post type

**Comment by EugenioPetulla** [comment]
I know but it doesn't seems to work in the CPT main archive. Look at the link I posted to you! The option is enabled in the dashboard but it doesn't seems to work for this archive, it works only in every archives of the same CPT but not for the principal one so... maybe we have to check why it happens and fix it! ;)

**Comment by EugenioPetulla** [comment]
@Mte90 What do you think if we use a simple check like this?

`if ( 'post_type' == get_post_type())` 

It should works in every page of the post type instead of doing a check for archive and for the singular pages. I think it should do the work perfectly and will save us a lot of of coding.

One option to enable it in the whole post type, and some options to do the traditional extra checks for taxonomies, categories, tags, post and pages.

**Comment by Mte90** [comment]
I have tried in the archive page with the glossary post type enabled in the settings the links are added without problems.

**Comment by EugenioPetulla** [comment]
maybe is a genesis related problem. We have to investigate it. Look at the website http://codeat.co/glossary/glossary

**Comment by Mte90** [comment]
Cool `codeat_glossary_auto_link` is not executed in the archive page with genesis.

**Comment by EugenioPetulla** [comment]
Because we are putting it into two filters that genesis use before passing it's own `genesis_do_content`

`add_filter( 'the_content', array( $this, 'codeat_glossary_auto_link' ) );`
`add_filter( 'the_excerpt', array( $this, 'codeat_glossary_auto_link' ) );`

**Comment by Mte90** [comment]
so we can add another filter specific for genesis

**Comment by EugenioPetulla** [comment]
But genesis_do_content is an action! T.T

**Comment by Mte90** [comment]
Uhm maybe we can alter the $post value

**Comment by EugenioPetulla** [comment]
Or maybe this could be the soultion.

http://www.carriedils.com/genesis-2-0-archive-settings-custom-post-types/

If it's not, you can open another issue in order to integrate it suddenly! (We found some genesis integration points at least!)
