### ISSUE TITLE
Doubled tooltip box

### ISSUE THREAD

**Issue by EugenioPetulla** [CodeAtCode/Glossary#14]
Every kind of tooltip I coose I have the same issue.

Is it an issue with our template or general one?

Link to reproduce it: http://codeat.co/glossary/hello-world/
![schermata da 2016-02-17 23-09-36](https://cloud.githubusercontent.com/assets/3589467/13126734/f9044f48-d5cb-11e5-8aac-130748450689.png)

**Comment by EugenioPetulla** [comment]
It seems to be related to the External URL I set up into the page. If I don't set an external URL everything it's ok! ;)

**Comment by EugenioPetulla** [comment]
No, I double checked now and it seems to appear also in internal linking.

**Comment by EugenioPetulla** [comment]
It's beacuse you are calling get_the_excerpt but we are filternig it so if another terms is in the excerpt it will popup too.

**Comment by Mte90** [comment]
Uhm infact I can see the code is duplicated i have to check that.

**Comment by Mte90** [comment]
I can't reproduce that problem...
$this->get_the_excerpt is custom and get direct from post_excerpt or content without filters.

**Comment by Mte90** [comment]
I have understand the bug, when there is a related term with the same name and this exist in the glossary content there is the problem
