### ISSUE TITLE
Make CSS of classic tooltip more readable

### ISSUE THREAD

**Issue by EugenioPetulla** [CodeAtCode/Glossary#15]
Bring the alpha color to lower level

`.tooltip-item {
    background: rgba(0,0,0,0.1);
}`
![schermata da 2016-02-17 23-27-00](https://cloud.githubusercontent.com/assets/3589467/13127165/4228123e-d5ce-11e5-88f0-24cf2bf0f7d4.png)

**Comment by Mte90** [comment]
what is the style choosen?

**Comment by EugenioPetulla** [comment]
classic
