### ISSUE TITLE
Genesis support

### ISSUE THREAD

**Issue by Mte90** [CodeAtCode/Glossary#2]

**Comment by EugenioPetulla** [comment]
@Mte90 dove lo metto, considerando che si tratta di un file solo apposito per genesis e io vorrei includerlo SOLO nel caso esiste genesis e sia attivo!

Mi dai una dritta per strutturare bene il progetto/file/cartella? :D

**Comment by Mte90** [comment]
In public/includes e lo includiamo nel costruct del file class-glossary.php

**Comment by EugenioPetulla** [comment]
Ok :)

**Comment by EugenioPetulla** [comment]
Non è possibile attualmente aggiungere nessun supporto per genesis poiché non esiste uno schema.org adatto per il glossario.

Per ora chiudo la issue.
