### ISSUE TITLE
Link only the first occurrence in the same page

### ISSUE THREAD

**Issue by EugenioPetulla** [CodeAtCode/Glossary#20]
We need an option to activate this feature and we have to understand how to implement it.

Maybe a can do another regex just for this purpose.

@Mte90 any suggestion?

**Comment by Mte90** [comment]
Yes the only solution is a regex executed only on the first occurence.

**Comment by EugenioPetulla** [comment]
Are you able to point me on the right path or is all on my shoulders? :D

**Comment by Mte90** [comment]
Uhm i have no idea for that, someone suggest to use preg_match but not support arrays...

**Comment by EugenioPetulla** [comment]
Ok, I found the answer.

`$text = preg_replace( $words, $links, $text, 1 );`

@Mte90 now you have to put an option in the panel. Do you want I open an issue for it?

**Comment by EugenioPetulla** [comment]
It is the opposite of what we had to achieve! XD

I'll fix it! XD
