### ISSUE TITLE
Provide a shortcode and a function to render actual widgets in other template parts

### ISSUE THREAD

**Issue by EugenioPetulla** [CodeAtCode/Glossary#25]
Following this discussion on wordpress.org: https://wordpress.org/support/topic/bugs-report-while-using-the-plugin and https://wordpress.org/support/topic/pages-with-a-list-of-glossary-terms

*Shortcodes*

- [x] Last Glossary Terms
- [x] Glossary Terms
- [x] Glossary Categories

*Widget*

- [x] Last Glossary Terms
- [x] Glossary Categories

**Comment by EugenioPetulla** [comment]
@Mte90 I need some directions: I know where to place shortcodes code but I'm a little in trouble with functions. public/class-glossary.php is a good chooice? It's ok if I just code the shortcodes like those functions' wrappers?

**Comment by Mte90** [comment]
In public/includes you can add a file here for shortcode.

**Comment by EugenioPetulla** [comment]
@Mte90 yes, and it's ok. But I asked where to place theme functions and if it's a good idea to built the shortcodes as wrappers of those functions.

**Comment by Mte90** [comment]
is ok :-)
