### ISSUE TITLE
Problema su ricerca

### ISSUE THREAD

**Issue by MaxDevergori** [CodeAtCode/Glossary#27]
Ciao ragazzi,
una domanda: ho installato il vostro plugin Glossary [che reputo il migliore in circolazione] però succede una cosa strana con la funzione di ricerca sia di WordPress che di Relevanssi (ma anche altri plugin simili). Praticamente non appena installo Glossary, la funzionalità di ricerca (tramite box) esclude le "pagine" dalla ricerca. Non appena disattivo Glossary, la ricerca ritorna a funzionare normalmente e quindi anche nelle pagine. Sapete darmi qualche indicazione? o dipende forse da qualche conflitto interno al mio WordPress?
Grazie mille!

**Comment by Mte90** [comment]
Si nel plugin obblighiamo alla ricerca nei soli post https://github.com/CodeAtCode/Glossary/blob/master/public/class-glossary.php#L186
Dovremmo correggere in modo che aggiunga solo il post type senza resettare.

**Comment by MaxDevergori** [comment]
Capisco... Grazie!

**Comment by MaxDevergori** [comment]
PS: non c'è modo di effettuare la modifica dal mio wp? dovrebbe essere solo una questione di modifica di variabile credo...

**Comment by MaxDevergori** [comment]
risolto! grazie per la dritta!
