### ISSUE TITLE
Allow internal links

### ISSUE THREAD

**Issue by jstoeffler** [CodeAtCode/Glossary#31]
Instead of the external link, I'd like to provide an option to link to a specific:

- post
- page
- custom post type
- category
- ...

Right now, I use the URL, but it'd be great if the link were more "solid".

**Comment by EugenioPetulla** [comment]
I like the idea but I think it's good to leave the external url option untouched, maybe we can add an extra field for internal linking purposes.

We can consider something like this: https://github.com/WebDevStudios/CMB2-Post-Search-field

**Comment by jstoeffler** [comment]
Yes, you definitely want to keep the external link.
I had a quick look and the CMB2 looks good but doesn't handle link to categories (which is one thing I'd love to have personally)

**Comment by EugenioPetulla** [comment]
@Mte90 I think you can point us in the right direction.

Do you think is useful to extend CMB2 in order to list taxonomies in a select, like you did with users, or maybe we can consider something better?

I think it's a good feature to have in order to create a more consistent internal linking.

**Comment by Mte90** [comment]
My version of that field is better for the UX https://github.com/Mte90/CMB2-Post-Search-field and is possible to set the post type but if we want something in live I have to improve.
For the taxonomy check is the same situation.

**Comment by EugenioPetulla** [comment]
I love your solution! Well done with the UX, I'm surprised about backbone usage but woow :+1: 

I'm thinking about a radio or a select with this 3 options:

* External URL - Default
* Internal Post/Page
* Internal Taxonomy

And a simple js hide trick in order to display the relative input field.

In this way we can keep all in separates values.

**Comment by Mte90** [comment]
So the 1.1.0 will have a picker for post type and an area for the external with a choice.
To add the support of taxonomy I have to develop a new fields with a new interface and we have no time to work on it.
