### ISSUE TITLE
"..." is added after the tooltip excerpt, even if it's not truncated.

### ISSUE THREAD

**Issue by jstoeffler** [CodeAtCode/Glossary#32]
If I have an excerpt shorter than the length of the excerpt, the plugin still add "..." at the end (only if no external link is provided)

**Comment by EugenioPetulla** [comment]
I think this is unpreventable unless we count the excerpt lenght and compare it to the given option in the panel. In case excerpt is shorter we don't print out the ellipses @Mte90
