### ISSUE TITLE
Link is added if search string is at the end of the word

### ISSUE THREAD

**Issue by jstoeffler** [CodeAtCode/Glossary#33]
Use case:

Search term:

    virus

Text: 

    You should use an antivirus to protect your computer.

Result:

    You should use an anti<a [...]>virus</a> to protect your computer.

**Comment by EugenioPetulla** [comment]
I'm working on this issue, actually is a regex check that I've to implement but I'm reaching an high complexity level so I want to be sure that it will not break something.

Priority issue, thanks for reporting. :+1:

**Comment by jstoeffler** [comment]
I've never done unit tests on wp plugins, but this seems like a use case where they'd be helpful

**Comment by jstoeffler** [comment]
Btw, this doesn't happen when the string is in the middle or at the beginning of the word

**Comment by EugenioPetulla** [comment]
Fixed, just wait until next release or follow this commit and try a temporary patch: https://github.com/CodeAtCode/Glossary/commit/5365745eab1c041c3abc31cea07872deb777fd3f

:)
