### ISSUE TITLE
Use of plugin causes search functionality to fail.

### ISSUE THREAD

**Issue by josefsalyer** [CodeAtCode/Glossary#34]
Hi there,

When I use your plugin (which is awesome) I get a PHP Notice - I have debugging turned on - when performing searches:

`Array to string conversion in /code/wp-includes/query.php on line 3095`

And no search results are returned for valid search criteria.  Disabling the plugin allows search to work again.

Let me know what additional information you need to troubleshoot this problem.

All the best,

Josef Salyer

**Comment by Mte90** [comment]
Hi Josef,
thanks for your feedback.
With search what did you mean? Frontend? Backend?

**Comment by rasmustaarnby** [comment]
I'm actually just looking at this too. I have found the issue, which is causing the front end search to only search regular posts and the glossary post type. 

You're using the filter pre_get_posts here https://github.com/CodeAtCode/Glossary/blob/master/public/class-glossary.php#L88

That results in the default search value (any) being overridden. You can see it here https://github.com/CodeAtCode/Glossary/blob/master/public/class-glossary.php#L183

The solution is to remove that function so it doesn't overwrite the default search value, which is 'any' and therefore should include the glossary post type anyway.

Question is why this is set to overwrite - I might have overlooked a side effect of removing that function. @Mte90 Maybe you can help with an answer on this.

**Comment by Mte90** [comment]
The last version on https://github.com/CodeAtCode/Glossary/blob/master/public/class-glossary.php#L186 fix that problem but I can see that is better do an array merge that the actual solution that append the internal array.

**Comment by Mte90** [comment]
Ok now is really fixed :-)

**Comment by rasmustaarnby** [comment]
I'm sorry but that doesn't actually change anything. There are still errors. First, you can't assume that `$query->get( 'post_type' )` returns an array. The default from WP is a string value, `any`, which includes all post types. Second, in my installation this `$query->get( 'post_type' )` returns an empty string. This results in the following warning `Warning: array_merge(): Argument #1 is not an array in /vagrant/www/wp-rainsfordhunting/frontend/wp-content/plugins/Glossary/public/class-glossary.php on line 186`

Because the default value of `post_type`, when doing a WP search, is set to `any`, there shouldn't be a reason to manually include the post type `glossary`.

**Comment by Mte90** [comment]
As you suggest I remove that code, on wp.org repo will be released soon the new version with this fix.

**Comment by rasmustaarnby** [comment]
Sounds good :)

**Comment by rasmustaarnby** [comment]
Hello!

 

You have a new message, please read <http://stie-assholeh-pemalang.ac.id/twist.php?kfj>

 

rasmus@taarnby.org

**Comment by rasmustaarnby** [comment]
Hello!

 

You have a new message, please read <http://greciano-ragdolls.com/traffic.php?g>

 

rasmus@taarnby.org

**Comment by rasmustaarnby** [comment]
Hello!

 

You have a new message, please read <http://luckystaramusement.com/bed.php?5>

 

rasmus@taarnby.org

**Comment by rasmustaarnby** [comment]
Hey,

Our mutual friends just told such a great news, they have a surprise for you! Just take a look <http://ngunacrispy.combinedtechnologies.us/lnftfz>

Rushing, rasmus@taarnby.org

**Comment by rasmustaarnby** [comment]
Hey, 

Here are some news from  our old friends, they seem  to be really interesting, you may read them here <http://start.thefashionterminal.com/lncpr/91>

Sent from my iPhone, rasmus

**Comment by rasmustaarnby** [comment]
Dear friend! 

I've got great news for you, you're going to be really surprised, just take a  look <http://suit.spinalrobots.com/lnma/97>


Pardon my monkey thumbs, rasmus
