### ISSUE TITLE
HTML page for glossary terms don't seem to auto-create...

### ISSUE THREAD

**Issue by kdeuler** [CodeAtCode/Glossary#40]
Hi. Perhaps you can assist with a basic question: In this page:

http://cadtogadget.com/glossary-test/

... tool tips for the two terms (same definition) pops up correctly. However, when I click on the "More" or the link term, in the tool tip, I get a "Page not found" error. When I edit the glossary term, I can see where it indicates the permalink is " http://cadtogadget.com/glossary/high-speed-machining-hsm/". However, that page doesn't seem to exist. Please advise if I'm missing a step.  Thanks, and I look forward to using this plugin!

**Comment by kdeuler** [comment]
... Oh sorry. I just realized that I needed to update the Permalinks in Settings.

Other questions: 
1) Do you have instructions on how to use CSS to alter the look of the tool tips?
2) Is there a way to list all terms in an automatically updated "glossary page" so that readers can browse through them?

Thanks!

**Comment by Mte90** [comment]
For the question 2 now the 1.1.* have the shortcode, so check the changelog for it.
For the css part we are working for a customizer support but the only way as developer can I suggest it is to learn CSS (or do a specific question).

For the permalink part we are working on it to find a solution.
