### ISSUE TITLE
Bug: Ver 1.1.1 interferes with search

### ISSUE THREAD

**Issue by dpg2012** [CodeAtCode/Glossary#42]
I believe ver. 1.1.1 contains a bug that interferes with WP's search function. All searches (except for glossary items) result in "not found". A glossary item links only to it's custom post and not the original source. Tested on WP 4.5.2 and Twenty Fourteen and Twenty Sixteen.

**Comment by Mte90** [comment]
There is an option now in the settings panel that add the search support for terms, you can disable it from that panel

**Comment by dpg2012** [comment]
Understood. The issue is that general searches are not working.

**Comment by Mte90** [comment]
Can you explain better?
With the options disabled the search not work?
With the options enabled the search not work?

**Comment by dpg2012** [comment]
I can no longer reproduce the error. Truly, I am confused.
In trying to identify the source of the "problem", I looked for some incompatibility with other plugins by disabling all of them except Glossary and then re-enabling them one-by-one. By the time I had re-enabled them all, I was unable to detect a problem.
So, I was either 1) wrong when I said that search wasn't working or 2) enabling and re-enabling other plugins fixed the issue. 
I would agree with marking this bug as resolved unless and until someone else reports the error. Sorry for the inconvenience.

**Comment by Mte90** [comment]
This are the ticket that i prefer that not require a check in the code and they are magically fixed :-D
