### ISSUE TITLE
Problems with polylang

### ISSUE THREAD

**Issue by Mte90** [CodeAtCode/Glossary#43]
https://wordpress.org/support/topic/conflict-with-psychological-tests-quizzes?replies=9#post-8546491

**Comment by wickedpuppy** [comment]
Thanks for the assistance!

I'm experiencing the same problem also with https://wordpress.org/plugins/enhanced-tooltipglossary/

**Comment by Mte90** [comment]
I tested locally but I have no problem.
As I can see in the screen the problm probably is that you have set the test as in the category E of the taxonomy of glossary and not of the plugin.
So is not a problem of our plugin.

**Comment by wickedpuppy** [comment]
What's the "category E"?

**Comment by Mte90** [comment]
That screen https://i.imgur.com/iHnjNEt.jpg

**Comment by wickedpuppy** [comment]
That's my username.

**Comment by Mte90** [comment]
Cool XD
By the way I have no idea when happen the problem because locally doesn't happen :-/

**Comment by wickedpuppy** [comment]
My actual setup is polylang, + glossary + Psychological tests & quizzes.

Every time I create a new test, it shows up in the glossary page for that specific language.

I'll go ahead and make another clean test environment. How did you go about reproducing the issue?

**Comment by Mte90** [comment]
for me is a problem of polylang that I cannot do something because that page is generated automatically by wordpress and Glossary don't do nothing specific

**Comment by wickedpuppy** [comment]
Did you activate languages and translations on both glossary and wpt_tests custom post types and taxonomy?

In the polylang settings there's a session called "Custom post types and Taxonomies".

You have to activate that for both glossary and wpt_test.

I've just deployed a fresh WP installation with the default theme, polylang, glossary, and wpt_tests and the problem happens.

**Comment by Mte90** [comment]
tried again but nothing

**Comment by wickedpuppy** [comment]
I have 3 installations in 2 different environments where the problem consistently occurs.

Did you activate languages and translations on both glossary and wpt_tests custom post types and taxonomy?

**Comment by wickedpuppy** [comment]
I did the fourth, clean installation: default theme, only these three plugins and there you go again: on the glossary page I can see tests.

Could you please give me the detailed procedure you used to reproduce the error?

**Comment by Mte90** [comment]
So write the right procedure that create the problem:

* Install polylang
* configure 2 languages
* set one as default for all the post
* install the testing plugin
* create a test
* go the taxonomy archive page of glossary

This is my procedure, what are the difference with yours?

**Comment by wickedpuppy** [comment]
> Did you activate languages and translations on both glossary and wpt_tests custom post types and taxonomy?
> 
> In the polylang settings there's a session called "Custom post types and Taxonomies".
> 
> You have to activate that for both glossary and wpt_test

**Comment by Mte90** [comment]
with `configure 2 languages` i say that

**Comment by wickedpuppy** [comment]
![2016-06-22](https://cloud.githubusercontent.com/assets/13969852/16266015/ec186ee4-3882-11e6-9ce8-399a7da85e42.png)

Is your configuration like this?

Can I see a screenshot of your polylang configuration?

**Comment by Mte90** [comment]
So as I can see if i enable polylang (and check also test categories) the archives of the plugin are empty.
So this is a problem of polylang and not of our plugin, we cannot do something about it.

**Comment by wickedpuppy** [comment]
I'm ore inclined to believe that something is wrong with the way glossary retrieves the 'glossary' CPT with the term list.

What's the part of your code that build the /glossary/ page?

**Comment by Mte90** [comment]
Here: https://github.com/CodeAtCode/Glossary/blob/master/public/class-glossary.php#L76
we use a library that simplify the declaration of register of cpts and taxonomy

**Comment by EugenioPetulla** [comment]
Too standard to be a CPT related issue. I'm investigating deeply and I belive that there is a clash with polylang. That's not only an "our plugin" related issue. A lot of other major plugin declared a "not good compatibility with polylang".

I'm sorry for this but it's impossibile to be compatible with everything in the WordPress environment! T.T

**Comment by wickedpuppy** [comment]
Thank you, guys, for your effort. I truly appreciate it.

@EugenioPetulla, I'm aware that being compatible with everything is impossible.

I've already opened a ticket on the polylang support. I'd be really grateful if you could weigh in: https://wordpress.org/support/topic/polylang-mixes-up-custom-post-types?replies=1

No matter what, according to my researches, polylang at the moment is the best free option for a multilingual site. If you could make your plugin compatible with it, it would be great.

**Comment by EugenioPetulla** [comment]
@wickedpuppy yes, I'm following your ticket on the polylang's support and if we can do anything about it, I swear, we will! :)

**Comment by wickedpuppy** [comment]
So, it turned out that the wp-testing plugin is injecting 'wpt_test' post_types in virtually a good 80% of the standard wordpress loops, breaking everything that comes its way -_-

Feel free to forget this issue and let's pretend that nothing happened -_-

I cannot fathom how the developers of that plugin could leave such a huge compatibility issue lingering for so long, 'cause it probably messes up with any plugin using cpts archives.

Thanks a lot for your support!

**Comment by EugenioPetulla** [comment]
Don't worry, you are welcome! I hope to see you next time in completely different circumstances.

:)
