### ISSUE TITLE
Can I change the default single template?

### ISSUE THREAD

**Issue by lance1572** [CodeAtCode/Glossary#46]
Hi I would like to change the glossary term template from single to another custom template. Is this possible without hacking the plugin files?

Thanks!

**Comment by Mte90** [comment]
for html? for css? for the wsecond one as developer you can do it in your template, for the first not the classes are define for work with the css template included.

**Comment by EugenioPetulla** [comment]
You dont' have to hack anything, just create your own `single-glossary.php` template in the root folder of your theme and it will overwrite the standard single one.

**Comment by lance1572** [comment]
Thank you for the directions! That worked!
