### ISSUE TITLE
Alphabetical order

### ISSUE THREAD

**Issue by JoeCrickets** [CodeAtCode/Glossary#47]
Hi,
I have just started using this fantastic plug-in, it is just what I was lookin' for, but I don't know how to put the terms in alphabetical orders, terms are displayed in chronological order only, 
could you please me what should do?
Thanks a lot

Giuseppe

**Comment by Mte90** [comment]
in what page are not display in alphabetical order?

**Comment by EugenioPetulla** [comment]
@JoeCrickets did you checked the right option in the panel?

![schermata da 2016-06-26 00-43-18](https://cloud.githubusercontent.com/assets/3589467/16359509/711c3826-3b37-11e6-8ffa-88b40c6111c7.png)

**Comment by JoeCrickets** [comment]
Thank you for your reply,
I made a category page called glossary, where to display all items:
http://dharmaway.altervista.org/glossary-cat/glossario/
(The website is still under construction).
The widget in the sidebar works very well, but if it were possible I'd like
to have a page as well.

Thank you
Giuseppe

2016-06-26 0:46 GMT+02:00 Eugenio Petullà <notifications@github.com>:

> @JoeCrickets <https://github.com/JoeCrickets> did you checked the right
> option in the panel?
>
> [image: schermata da 2016-06-26 00-43-18]
> <https://cloud.githubusercontent.com/assets/3589467/16359509/711c3826-3b37-11e6-8ffa-88b40c6111c7.png>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/CodeAtCode/Glossary/issues/47#issuecomment-228574295>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ATNZY3BciHBEQXsms9NguxZvkNRcqEDXks5qPa_VgaJpZM4I-XYJ>
> .
>



-- 

*Giuseppe Grilli*
*Tel. 338 1940151*

**Comment by EugenioPetulla** [comment]
Ciao Giuseppe,
non ci stiamo capendo molto bene quindi direi di passare all'italiano :)

Non capiamo se quello che ti serve a questo punto è l'ordinamento alfabetico (e se così fosse già esiste una pagina archivio che puoi trovare qui: http://dharmaway.altervista.org/glossary/) oppure se hai bisogno di una pagina con una lista ordinata DI LETTERE in stile indice.

Se fosse quest'ultima la cosa che chiedi, purtroppo al momento non è disponibile e credo che sarà inclusa a brevissimo nelal versione Pro, che prevederà anche il supporto diretto, un customizer per i tooltip e shortcode aggiuntivi per varie altre personalizzazioni più specifiche.

Puoi comunque inserire il widget in una pagina usando un plugin che trasforma i widget in shortcode, ne esistono tanti, uno che mi sento di consigliare è https://it.wordpress.org/plugins/amr-shortcode-any-widget/

**Comment by JoeCrickets** [comment]
Ciao Eugenio,
grazie, mi hai risolto il problema dovuto alla mia insufficiente conoscenza
di Wordpress,
avevo bisogno di una pagina che mostrasse tutti i termini in ordine
alfabetico.
In effetti ho sbagliato a linkare la voce Glossario dal menu in alto (
http://dharmaway.altervista.org/glossary-cat/glossario/) che mi crea una
pagina dove i termini non erano in ordine alfabetico.
Mentre l'indirizzo che mi hai inviato tu lo visualizza correttamente (
http://dharmaway.altervista.org/glossary/).

Grazie ancora e buona giornata
Giuseppe

Il giorno 28 giugno 2016 01:22, Eugenio Petullà <notifications@github.com>
ha scritto:

> Ciao Giuseppe,
> non ci stiamo capendo molto bene quindi direi di passare all'italiano :)
>
> Non capiamo se quello che ti serve a questo punto è l'ordinamento
> alfabetico (e se così fosse già esiste una pagina archivio che puoi trovare
> qui: http://dharmaway.altervista.org/glossary/) oppure se hai bisogno di
> una pagina con una lista ordinata DI LETTERE in stile indice.
>
> Se fosse quest'ultima la cosa che chiedi, purtroppo al momento non è
> disponibile e credo che sarà inclusa a brevissimo nelal versione Pro, che
> prevederà anche il supporto diretto, un customizer per i tooltip e
> shortcode aggiuntivi per varie altre personalizzazioni più specifiche.
>
> Puoi comunque inserire il widget in una pagina usando un plugin che
> trasforma i widget in shortcode, ne esistono tanti, uno che mi sento di
> consigliare è https://it.wordpress.org/plugins/amr-shortcode-any-widget/
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/CodeAtCode/Glossary/issues/47#issuecomment-228905252>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ATNZY1IiaagMUNCSAo0lawSVwQ0Yh_Dwks5qQFtAgaJpZM4I-XYJ>
> .
>



-- 

*Giuseppe Grilli*
*Tel. 338 1940151*
