### ISSUE TITLE
Woocommerce seacrh prducts does not function

### ISSUE THREAD

**Issue by MicroKloon** [CodeAtCode/Glossary#50]
Hi,

Great plugin! Better and more advanced then most commercial offering, keep up the good work!

That said.....
When I activate the plugin then the search for a Woocommerce product in the backend does not function anymore. I get an error of 'invalid content type'. What problem can that be?

**Comment by Mte90** [comment]
Well we need more information about the error to understand the problem

**Comment by MicroKloon** [comment]
I get an error of 'invalid content type

**Comment by Mte90** [comment]
A screen?

**Comment by MicroKloon** [comment]
![phoxo1](https://cloud.githubusercontent.com/assets/16863120/17517729/00607616-5e45-11e6-974c-0e3e0c27256b.png)

**Comment by Mte90** [comment]
Uhm as I can see from the url there is a bug, you tried to turn off the search option in the plugin settings panel?

**Comment by Mte90** [comment]
any hint?

**Comment by EugenioPetulla** [comment]
@MicroKloon maybe you were able to solve this problem but we need some ffedback if it's possibile in order to understand if we have to patch something or not.

Thank you in advice for your help! 😃

**Comment by Mte90** [comment]
We close that, in case of updates we will open again.

**Comment by KloonDuino** [comment]
oops sorry, no it is not fixed.
I installed another glossary plugin and that works great.

**Comment by Mte90** [comment]
As I can see in the code the 1.2.0 will fix this problem
