### ISSUE TITLE
Term definition is not showing

### ISSUE THREAD

**Issue by MamdouhSar** [CodeAtCode/Glossary#52]
Hey, I'm trying to use your useful plugin, however when I write down the definition for a term, it does not show on the webpage. The Glossary terms and category show and there is no problem with them, however once I click on one of the terms there is no definition.

Thank you.

**Comment by Mte90** [comment]
when you say show on the webpage you are talking about the tooltip on the hover or there is no link in the text for that term?

**Comment by MamdouhSar** [comment]
Here I will show you with these screenshots, sorry for the arabic language but I hope you will get the idea. 
![screen shot 2016-08-24 at 11 42 44 pm](https://cloud.githubusercontent.com/assets/20500558/17947383/1a111ff4-6a55-11e6-8349-f9bd9d785967.png)
Above is the term I have created

![screen shot 2016-08-24 at 11 43 12 pm](https://cloud.githubusercontent.com/assets/20500558/17947385/1a17b88c-6a55-11e6-9e2f-1369b3aaf512.png)
Here is the glossary category page, here it shows the term definition and no problem

![screen shot 2016-08-24 at 11 43 35 pm](https://cloud.githubusercontent.com/assets/20500558/17947384/1a1792da-6a55-11e6-8491-0ba10c1bd4cd.png)
However, when I click on the term and go to its link, the definition does not show

**Comment by Mte90** [comment]
uhm maybe the problem is the rtl and the tooltip not support them

**Comment by Mte90** [comment]
The 1.1.0 don't support something different from utf-8, the 1.20 will have the support for multibyte and the other standards
