### ISSUE TITLE
Adding text and links to the index page "url.com/glossary"

### ISSUE THREAD

**Issue by edgeglobal** [CodeAtCode/Glossary#54]
Hi, your plugin is great! well done. 
I have a question for optimal seo silo structure implementation. I would like to add text and links to the top and bottom of the index page. how is that possible?

thanks in advance

**Comment by Mte90** [comment]
What page? Are you talking about the archive index page?
In case you can do it using the wordpress hierarchy template system :-)

**Comment by Mte90** [comment]
I close, in case of other updates I will open again
