### ISSUE TITLE
/glossary doesn't show up, problems with the terms pages 

### ISSUE THREAD

**Issue by joeyoungblood** [CodeAtCode/Glossary#59]
Hi there I tried using your WordPress plugin for the education section of my site and hit a few issues. I noticed one of these showed up on your support forum but you marked the thread resolved even though it never was. 

1. No / glossary page. - This page doesn't show up at all, which kind of ruins the whole glossary plugin. I tried deactivating then reactivating the plugin as well as resaving my permalink settings. page: http://www.joeyoungblood.com/education/glossary/

2. The terms page itself has a few issues for me.
a. There is a "Prev" and "Next" link at the top. These show up even though I only have 1 term right now. It's super annoying and I'd actually like to not have them there at all. 
b. the term links to it's own page, I dont want it to do this and I can't find an option in the settings (i.e. a checkbox) to not link to the terms page from the terms page.
example terms page: http://www.joeyoungblood.com/education/glossary/memevertising/

**Comment by EugenioPetulla** [comment]
@joeyoungblood first of all thank you for this report.

1 - We will inviestigate on why this could happen, and I give the task to @Mte90 

2.a - This is a theme related stuff you can easily solve putting this rule into your css: `.single-glossary .post-navigation {display:none;}`

2.b. - We will work on this feature in the future, thank you for reporting.

**Comment by joeyoungblood** [comment]
Thanks for the CSS trick but it didn't work. My style.css file though is also empty, which is confusing.

**Comment by EugenioPetulla** [comment]
You can try with the "Custom CSS" module of jetpack. :)

**Comment by Mte90** [comment]
1 As said by Eugenio check that option

2.a I think also that is a theme feature and us cannot do so much for it.
2.b Are you talking about the title page? I guess that is again a theme issues

**Comment by joeyoungblood** [comment]
1. Checked and nothing. 
2a. Fixed it! My theme uses main.css apparently which was unable to be edited in editor. But it is now working: http://www.joeyoungblood.com/education/glossary/memevertising/
2b. Please visit the link above and notice the word 'memevertising' which is the word this page is about, it is a hyperlink to the same page. I do not want that (and no one should tbh)

**Comment by joeyoungblood** [comment]
This page might highlight my problem in #2b better, see the "Also Written As" section and notice all variations are linked to the same page. Why is that? http://www.joeyoungblood.com/education/glossary/black-hat/

**Comment by joeyoungblood** [comment]
Also, is there a CSS trick to get rid of the authorbox on these pages? The author box plugin I'm using doesn't have a way to do it, most likely because these are not custom post types.

**Comment by joeyoungblood** [comment]
I've tried everything to get /glossary to work: 
1. removed WP Super Cache
2. reinstalled WP Super Cache 
3. disabled WP Super Cache 
4. Flushed permalinks
5. Check the boxes in your image above and saved settings
6. Flushed permalinks
7. Unchecked the boxes in your image above and saved settings
8. Flushed permalinks 

noting appears to be working :/

**Comment by EugenioPetulla** [comment]
@joeyoungblood sorry for the delay in answering.

We are evaluating to put the feature of preventing linking the same term in the term page (2b) in the next Pro version.

For the other problems we can't do anything because is related to your website and theme, we provide this kind of support only for the pro owners. If you choose to upgrade your plan write us using the designated area "Contact Us" in your dashboard and check the flag "Technical Support" to keep in touch for specific support.

Thank you,
Eugenio

**Comment by joeyoungblood** [comment]
Eugenio,

Thanks, but that is not super helpful. I'd be happy to donate if it didn't feel like you offered a broken plugin and then told people you'd totally fix it if they just donated money.

**Comment by EugenioPetulla** [comment]
I'm sorry if you think we are not honest with our users but we have to respect people that choose to support us upgranding their plan in order to receive specific support.

Our plugin is totally free and there are plenty of reviews that says everything is working well, we try to do our best with customer care, just look at the time I'm spending on your problem here and at the solutions I give to your theme specific related problems. The code is here, open source on GitHub, if you think it's broke and we are only trying to steal your money  fork it and make your own version, we use a completely Free and Open Source License in order to make you inspect the code and fix it by yourself without any problem.

Tank you for your time spent reporting bugs and asking features, we appreciated the effort.

**Comment by joeyoungblood** [comment]
Hi there. I'm very thankful for the help you did offer, but as a marketer I'm trying to offer you insight to how your potential consumers might feel about your plugin not working out of the box and being told there is nothing that can be done without paying. I apologize if that offended you, that is not my intent. I am not a developer so there is little value in it for me to try and fork and make my own plugin, nor is there any value for me to pay you in hopes that the plugin works as advertised. That is the dilemma you are asking website owners to solve and I only wanted to make you aware of that so you can improve the quality of your service offering in the future. :)

Do you have anything I can try and the developer of my theme to try and understand why this wouldn't work, if it is my theme as you suggested there must be something I can ask them to fix?

**Comment by EugenioPetulla** [comment]
Try deactivating all your plugins and try switching to a default theme (like twenty-something). After you did it you will know if there is something wrong with our plugin. If everything will work try reactivating one thing at time so you can easily understand what plugin (or theme) cause the issue.

**Comment by joeyoungblood** [comment]
I deactivated everything (even glossary), moved to Twenty-Fourteen theme, and then reactivated the plugin and still nothing. I'll try on a fresh install here soon. What is your pro cost?

**Comment by EugenioPetulla** [comment]
Try with a fresh install first.

Actually the cost of the plugin is 29.99 dollars, you can see it directly from your plugin dashboard.

**Comment by joeyoungblood** [comment]
Ok, looking into it and trying this out over the weekend.
