### ISSUE TITLE
Considerare un widget per archivi alfabetici

### ISSUE THREAD

**Issue by EugenioPetulla** [CodeAtCode/Glossary#6]
Prendere spunto da questo plugin: https://wordpress.org/plugins/a2z-alphabetical-archive-links/

Eliminare tutta la parte relativa al resto dei cpt e dei post e integrarlo solo nel glossario.

Via le opzioni, il css e il counter dei post negli archivi.

**Comment by Mte90** [comment]
Per farlo devo studiare un modo per avere degli archivi che contengano parole che iniziano con una data lettera.

**Comment by Mte90** [comment]
Il plugin funziona e inietta del codice specifico nella query sql.
Posso rielaborare quel codice ma dobbiamo specificare nel readme che quella funzionalitá é basata su questo plugin.
