### ISSUE TITLE
Having loads of redirect errors

### ISSUE THREAD

**Issue by KloonDuino** [CodeAtCode/Glossary#60]
Hi,

Having loads of problems with redirects when a glossary term and a product-category name are the same.
All the problems go away when I deactivate your plugin.

WC-versie: 		2.6.9
WP-versie: 		4.7
WP Multisite: 		–
WP Memory Limit: 		1 GB
Serverinformatie: 		Apache/2.4.10
PHP-versie: 		7.0.14-1~dotdeb+8.1
PHP Post Max Size: 		24 MB
PHP Time Limit: 		300
PHP Max Input Vars: 		1000
cURL Versie: 		7.38.0, OpenSSL/1.0.1t
SUHOSIN Geïnstalleerd: 		–
MySQL-versie: 		5.7.17	
Max Upload Grootte: 		24 MB

**Comment by Mte90** [comment]
product-category is a taxonomy of what plugin? In that way i can test it

**Comment by KloonDuino** [comment]
woocommerce
