### ISSUE TITLE
Change Labels to CPT's menù items

### ISSUE THREAD

**Issue by EugenioPetulla** [CodeAtCode/Glossary#9]
![schermata da 2016-02-17 19-16-29](https://cloud.githubusercontent.com/assets/3589467/13119793/2b87efea-d5ab-11e5-824d-f0b8b47be654.png)
*"All Glossary"* -> **"All Glossary Terms"**
*"Add New Glossary"* -> **"Add Term to Glossary"**
*"Category"* -> **"Terms Categories"**

**Comment by Mte90** [comment]
![screenshot9](https://cloud.githubusercontent.com/assets/403283/13120228/227844d4-d5ad-11e5-8865-0b4cd5ef7585.png)

**Comment by EugenioPetulla** [comment]
<3
